namespace NetGore.Core.Enum;

public enum RaceEnum
{
    None = 0,
    Dragonborn = 1,
    Dwarf = 2,
    Elf = 3,
    Gnome = 4,
    HalfElf = 5,
    Halfling = 6,
    HalfOrc = 7,
    Human = 8,
    Tiefling = 9,
    Aasimar = 10,
    Catfolk = 11,
    Changeling = 12,
    Dhampir = 13,
    Fetchling = 14,
    Goblin = 15,
    Hobgoblin = 16,
    Kitsune = 17,
    Kobold = 18,
    Merfolk = 19,
    Nagaji = 20,
    Oread = 21,
    Ratfolk = 22,
    Samsaran = 23,
    Suli = 24,
    Svirfneblin = 25,
    Sylph = 26,
    Tengu = 27,
    Undine = 28,
    Vanara = 29,
    Vishkanya = 30,
    Wayang = 31,
    Strix = 32,
    Ifrit = 33,
    Gillman = 34,
    Orc = 35,
    Grippli = 36,
    Duergar = 37,
}
