namespace NetGore.Core.Enum;

public enum RacialTraitEnum
{
    None = 0,
    Goldsniffer = 1,
    Highlander = 2,
    MilitiaVeteran = 3,
    SurfaceStranger = 4,
    SavannaChild = 5,
    Civilized = 6,
    VagabondChild = 7,
    LogRoller = 8,
    RiverRat = 9,
    DesertChild = 10,
    SeaSouled = 11,
    TundraChild = 12,
    ScholaroftheGreatBeyond = 13,
    TunnelFighter = 14,
    Brewmaster = 15,
    Orphaned = 16,
    KinGuardian = 17,
    Forlorn = 18,
    AnimalFriend = 19,
    Rapscallion = 20,
    KinBond = 21,
    Scrapper = 22,
    Outcast = 23,
    WellInformed = 24,
    ChildoftheStreets = 25,
    FriendinEveryTown = 26,
    FrontierForged = 27,
    PovertyStricken = 28,
    LifeofToil = 29,
    BloodofDragons = 30,
    MagicalKnack = 31,
    FocusedMind = 32,
    Suspicious = 33,
    Bullied = 34,
    Influence = 35,
    Champion = 36,
    Reactionary = 37,
    DenytheReaper = 38,
    FearlessDefiance = 39,
    Arisen = 40,
}
