<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NetGore.Features.Client_</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\.NetGore\NetGore.csproj" />
    <ProjectReference Include="..\NetGore.Features\NetGore.Features.csproj" />
  </ItemGroup>

</Project>
