<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\d20\NetGore.Core\NetGore.Core.csproj" />
    <ProjectReference Include="..\.NetGore\NetGore.csproj" />
    <ProjectReference Include="..\NetGore.Core\NetGore.Core.csproj" />
    <ProjectReference Include="..\NetGore.Db\NetGore.Db.csproj" />
    <ProjectReference Include="..\NetGore.Features\NetGore.Features.csproj" />
  </ItemGroup>

</Project>
